# Generated by Django 5.1 on 2024-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birthdate', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=255)),
                ('street', models.TextField(max_length=255)),
                ('passport_number', models.IntegerField(null=True)),
                ('passport_letter', models.TextField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WAITING', 'Waiting'), ('CANCELED', 'Canceled')], default='NEW', max_length=10)),
            ],
        ),
    ]
